=== MonicaEA/Ludoteca-DAM-Intermodular/src/RetroJuegos/src/main/resources/com/retrojuegos/retrojuegos/xml/esquema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="texto50Regla">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="texto100Regla">
        <xs:restriction base="xs:string">
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tituloRegla">
        <xs:restriction base="xs:string">
            <xs:maxLength value="150"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="emailRegla">
        <xs:restriction base="xs:string">
            <xs:maxLength value="100"/>
            <xs:pattern value=".+@.+\..+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tipoStockRegla">
        <xs:restriction base="xs:string">
                <xs:enumeration value="comun"/>
                <xs:enumeration value="propio"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="tipoEstadoRegla">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PRECINTADO"/>
            <xs:enumeration value="COMPLETO"/>
            <xs:enumeration value="CAJA SIN MANUAL"/>
            <xs:enumeration value="SOLO JUEGO"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="precioRegla">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="8"/>
            <xs:fractionDigits value="2"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="usuarioTipo">
        <xs:sequence>
            <xs:element name="nombre" type="texto50Regla" minOccurs="1"/>
            <xs:element name="apellidos" type="texto100Regla" minOccurs="1"/>
            <xs:element name="email" type="emailRegla" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <!--regla para tipo de precios!-->
    <xs:complexType name="preciosTipo">
        <xs:sequence>
            <xs:element name="compra" minOccurs="1">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="precioRegla">
                            <xs:attribute name="moneda" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="venta_estimado" minOccurs="1">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="precioRegla">
                            <xs:attribute name="moneda" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="estadoTipo">
        <xs:sequence>
            <xs:element name="tipo" type="tipoStockRegla" minOccurs="1"/>
            <xs:element name="estado" type="tipoEstadoRegla" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="videojuegoTipo">
        <xs:sequence>
            <xs:element name="titulo" type="tituloRegla" minOccurs="1"/>
            <xs:element name="plataforma" type="texto50Regla" minOccurs="1"/>
            <xs:element name="genero" type="texto50Regla" minOccurs="1"/>
            <xs:element name="precios" type="preciosTipo" minOccurs="1"/>
            <xs:element name="stock_info" type="estadoTipo" minOccurs="1"/>
            <xs:element name="fecha_registro" type="xs:date" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="usuarioReg" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:element name="retro_inventario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuarios" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="usuario" type="usuarioTipo" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="catalogo" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="videojuego" type="videojuegoTipo" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:string" fixed="1.0" use="required"/>
        </xs:complexType>
    </xs:element>

    </xs:schema>

=== MonicaEA/Ludoteca-DAM-Intermodular/src/RetroJuegos/src/main/resources/com/retrojuegos/retrojuegos/xml/videojuegos_exportados.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<retro_inventario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="esquema.xsd">
    <usuarios>
        <usuario id="u1">
            <nombre>Mónica</nombre>
            <apellidos>Espiñeira</apellidos>
            <email>monica.espineira1988@gmail.com</email>
        </usuario>
        <usuario id="u2">
            <nombre>Beatriz</nombre>
            <apellidos>Ferreira</apellidos>
            <email>bettyfer@gmail.com</email>
        </usuario>
    </usuarios>
    <catalogo>
        <videojuego id="v14" usuarioReg="u1">
            <titulo>Medievil</titulo>
            <plataforma>PSX</plataforma>
            <genero>Aventuras</genero>
            <precios>
                <compra moneda="EUR">20.0</compra>
                <venta_estimado moneda="EUR">35.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>propio</tipo>
                <estado>COMPLETO</estado>
            </stock_info>
            <fecha_registro>2026-05-01</fecha_registro>
        </videojuego>
        <videojuego id="v17" usuarioReg="u1">
            <titulo>Monkey Island</titulo>
            <plataforma>PS2</plataforma>
            <genero>Aventuras</genero>
            <precios>
                <compra moneda="EUR">10.0</compra>
                <venta_estimado moneda="EUR">25.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>propio</tipo>
                <estado>COMPLETO</estado>
            </stock_info>
            <fecha_registro>2026-05-03</fecha_registro>
        </videojuego>
        <videojuego id="v12" usuarioReg="u1">
            <titulo>F1 GRAN PRIIX</titulo>
            <plataforma>Nintendo NES</plataforma>
            <genero>Deportes</genero>
            <precios>
                <compra moneda="EUR">10.0</compra>
                <venta_estimado moneda="EUR">20.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>comun</tipo>
                <estado>SOLO JUEGO</estado>
            </stock_info>
            <fecha_registro>2026-04-29</fecha_registro>
        </videojuego>
        <videojuego id="v15" usuarioReg="u1">
            <titulo>Fifa 99</titulo>
            <plataforma>PSX</plataforma>
            <genero>Deportes</genero>
            <precios>
                <compra moneda="EUR">10.0</compra>
                <venta_estimado moneda="EUR">20.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>propio</tipo>
                <estado>SOLO JUEGO</estado>
            </stock_info>
            <fecha_registro>2026-05-02</fecha_registro>
        </videojuego>
        <videojuego id="v2" usuarioReg="u1">
            <titulo>Super Mario</titulo>
            <plataforma>Game Boy</plataforma>
            <genero>Plataformas</genero>
            <precios>
                <compra moneda="EUR">5.0</compra>
                <venta_estimado moneda="EUR">15.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>propio</tipo>
                <estado>SOLO JUEGO</estado>
            </stock_info>
            <fecha_registro>2026-04-18</fecha_registro>
        </videojuego>
        <videojuego id="v3" usuarioReg="u1">
            <titulo>Donkey Kong</titulo>
            <plataforma>Nintendo GameCube</plataforma>
            <genero>Plataformas</genero>
            <precios>
                <compra moneda="EUR">5.0</compra>
                <venta_estimado moneda="EUR">15.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>comun</tipo>
                <estado>COMPLETO</estado>
            </stock_info>
            <fecha_registro>2026-04-20</fecha_registro>
        </videojuego>
        <videojuego id="v10" usuarioReg="u1">
            <titulo>pepito</titulo>
            <plataforma>PS2</plataforma>
            <genero>Plataformas</genero>
            <precios>
                <compra moneda="EUR">10.0</compra>
                <venta_estimado moneda="EUR">150.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>comun</tipo>
                <estado>CAJA SIN MANUAL</estado>
            </stock_info>
            <fecha_registro>2026-04-27</fecha_registro>
        </videojuego>
        <videojuego id="v11" usuarioReg="u1">
            <titulo>Tomb Raider</titulo>
            <plataforma>PSX</plataforma>
            <genero>Plataformas</genero>
            <precios>
                <compra moneda="EUR">25.0</compra>
                <venta_estimado moneda="EUR">45.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>comun</tipo>
                <estado>CAJA SIN MANUAL</estado>
            </stock_info>
            <fecha_registro>2026-04-28</fecha_registro>
        </videojuego>
        <videojuego id="v13" usuarioReg="u1">
            <titulo>Super Mario 2</titulo>
            <plataforma>Game Boy</plataforma>
            <genero>Plataformas</genero>
            <precios>
                <compra moneda="EUR">10.0</compra>
                <venta_estimado moneda="EUR">25.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>comun</tipo>
                <estado>CAJA SIN MANUAL</estado>
            </stock_info>
            <fecha_registro>2026-05-01</fecha_registro>
        </videojuego>
        <videojuego id="v1" usuarioReg="u1">
            <titulo>The Legend of Zelda</titulo>
            <plataforma>Nintendo NES</plataforma>
            <genero>RPG</genero>
            <precios>
                <compra moneda="EUR">35.0</compra>
                <venta_estimado moneda="EUR">120.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>comun</tipo>
                <estado>COMPLETO</estado>
            </stock_info>
            <fecha_registro>2026-04-15</fecha_registro>
        </videojuego>
        <videojuego id="v9" usuarioReg="u1">
            <titulo>Zelda</titulo>
            <plataforma>Nintendo GameCube</plataforma>
            <genero>RPG</genero>
            <precios>
                <compra moneda="EUR">100.0</compra>
                <venta_estimado moneda="EUR">1200.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>propio</tipo>
                <estado>PRECINTADO</estado>
            </stock_info>
            <fecha_registro>2026-04-27</fecha_registro>
        </videojuego>
        <videojuego id="v16" usuarioReg="u1">
            <titulo>Tales of symphonia</titulo>
            <plataforma>Nintendo GameCube</plataforma>
            <genero>RPG</genero>
            <precios>
                <compra moneda="EUR">18.0</compra>
                <venta_estimado moneda="EUR">40.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>propio</tipo>
                <estado>COMPLETO</estado>
            </stock_info>
            <fecha_registro>2026-05-03</fecha_registro>
        </videojuego>
        <videojuego id="v8" usuarioReg="u1">
            <titulo>Double Dragon</titulo>
            <plataforma>Game Boy</plataforma>
            <genero>Shooter</genero>
            <precios>
                <compra moneda="EUR">25.0</compra>
                <venta_estimado moneda="EUR">100.0</venta_estimado>
            </precios>
            <stock_info>
                <tipo>propio</tipo>
                <estado>COMPLETO</estado>
            </stock_info>
            <fecha_registro>2026-04-27</fecha_registro>
        </videojuego>
    </catalogo>
</retro_inventario>

=== MonicaEA/Ludoteca-DAM-Intermodular/src/RetroJuegos/src/main/resources/com/retrojuegos/retrojuegos/xml/videojuegos.xml
<?xml version="1.0" encoding="UTF-8" ?>
<retro_inventario version="1.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="esquema.xsd">
    <usuarios>
        <usuario id="u1">
            <nombre>Mónica</nombre>
            <apellidos>Espiñeira</apellidos>
            <email>monica.espineira1988@gmail.com</email>
        </usuario>
        <usuario id="u2">
            <nombre>Beatriz</nombre>
            <apellidos>Ferreira</apellidos>
            <email>bettyfer@gmail.com</email>
        </usuario>
    </usuarios>

    <catalogo>
        <videojuego id="v1" usuarioReg="u1">
            <titulo>The Legend Of Zelda</titulo>
            <plataforma>Nintendo NES</plataforma>
            <genero>RPG</genero>

            <precios>
                <compra moneda="EUR">35.00</compra>
                <venta_estimado moneda="EUR">120.00</venta_estimado>
            </precios>

            <stock_info>
                <tipo>comun</tipo>
                <estado>COMPLETO</estado>
            </stock_info>

            <fecha_registro>2026-04-28</fecha_registro>
        </videojuego>

        <videojuego id="v2" usuarioReg="u2">
            <titulo>Sonic</titulo>
            <plataforma>Sega MegaDrive</plataforma>
            <genero>Plataformas</genero>

            <precios>
                <compra moneda="EUR">15.00</compra>
                <venta_estimado moneda="EUR">50.00</venta_estimado>
            </precios>

            <stock_info>
                <tipo>propio</tipo>
                <estado>CAJA SIN MANUAL</estado>
            </stock_info>

            <fecha_registro>2026-04-28</fecha_registro>
        </videojuego>
    </catalogo>
</retro_inventario>
